apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereum-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rpc-sample
        tier: ethereum-node
    spec:
      containers:
        - name: ethereum-cliant
          image: ethereum/client-go
          args: [
            "--light",
            "--rpc",
            "--rpcaddr", "0.0.0.0",
          ]
          volumeMounts:
            - name: chain
              mountPath: /root
          ports:
            - containerPort: 8545
            - containerPort: 30303
      volumes:
        - name: chain
          hostPath:
            path: /home/chain-data
