apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereum-node
  labels:
    app: ethereum-node
spec:
  replicas: 1
  teplate:
    metadata:
      labels:
        app: ethereum-node
    spec:
      containers:
        - image: ethereum/client-go
          name: ethereum-node
          args: ["--light", "--rpc", "--rpcaddr", "0.0.0.0"]
