apiVersion: v1
kind: Service
metadata:
  name: ethereum-node
  labels:
    app: ethereum-node
spec:
  type: LoadBalancer
  ports:
    - port: 8545
      targetPort: 8545
  selector:
    app: ethereum-node
