apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereum-node
  labels:
    app: ethereum-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ethereum-node
    spec:
      containers:
        - image: ethereum/client-go
          name: ethereum-node
          command: ["geth"]
          args: ["--light", "--rpc", "--rpcaddr", "0.0.0.0"]
          volumeMounts:
            - name: chain
              mountPath: /root
          ports:
            - containerPort: 8545
            - containerPort: 30303
      volumes:
        - name: chain
          hostPath:
            path: /home/chain-data
