apiVersion: v1
kind: Service
metadata:
  name: ethereum-node
  labels:
    app: rpc-sample
    tier: ethereum-node
spec:
  type: LoadBalancer
  ports:
    - port: 8545
      name: tcp
    - port: 30303
      name: udp
  selector:
    app: rpc-sample
    tier: ethereum-node
